### PR TITLE
Added a package.json to support install via npm

### PR DESCRIPTION
**Pull request by rasben**
I've fixed the issues with https://github.com/LeaVerou/multirange/pull/13 by @allbinmani

- Converting spaces to tabs (9ff852b)
- Fixing a merge conflict with the now-updated gh-pages branch: 6eb3745

Satisfied @LeaVerou ? :)

### CODE REVIEW

**Comment by LeaVerou** [comment]
Thanks!

**Comment by LeaVerou** [comment]
@rasben  
Apparently this completely broke the script and causes errors of module not being defined.
See: https://github.com/LeaVerou/multirange/issues/27 (except this is not just in IE, it happens everywhere)

**Comment by rasben** [comment]
@LeaVerou 
WTF? Didn't @allbinmani test it?
I recall I tested it originally, back when @allbinmani made his first pull request - the reason i fixed it recently was to fix a @todo i found in my own codebase.

I assumed you had a test environment for this also 

Anyway, seeing as this is the only PR that has been merged since then, I guess you'll have to revert to the previous commit (c136d150f78a1223c9d993d5e3283553d7c4cdcc) and force push it onto the gh-pages branch?

Although it's not my code originally, I'll try to find time during this week to fix the errors, so we hopefully can get this into the repo eventually

Sorry for this crap :/

**Comment by LeaVerou** [comment]
> WTF? Didn't @allbinmani test it?

Apparently not! I was surprised as well.

> I assumed you had a test environment for this also

I tend to merge those types of PRs very quickly, since it's usually boilerplate code. I should be more careful in the future!

> Anyway, seeing as this is the only PR that has been merged since then, I guess you'll have to revert to the previous commit (c136d15) and force push it onto the gh-pages branch?

I hadn't noticed it was the last one, thanks. Done that now.

> Although it's not my code originally, I'll try to find time during this week to fix the errors, so we hopefully can get this into the repo eventually

Thank you! Appreciate it.

> Sorry for this crap :/

Don't be, the error was in the original PR, you were just trying to help. :) It's also my fault for not looking more carefully before merging, it would've been very obvious if I just reviewed the diff properly.

**Pull request merged**
