### PR TITLE
Made polyfill not apply on SSR

### PR DESCRIPTION
**Pull request by totalolage**
This was preventing the NPM package from working with my NEXT project.

### CODE REVIEW

**Review by LeaVerou — CHANGES_REQUESTED** [review]
Hi there, thanks for the PR!

I would prefer to test for the functionality that we actually need, in this case something like

```js
if (typeof self === undefined || !self.HTMLInputElement) {
	return;
}
```

Also, minor, but we use tabs for indentation.

**Review by LeaVerou — CHANGES_REQUESTED** [review]
Thanks for the quick response. Unfortunately, using optional chaining here would make it throw on many of the supported browsers.

Also, if you don't include `typeof self === "undefined"`, it can still throw in your envirnoment.

**Comment by totalolage** [comment]
> Thanks for the quick response. Unfortunately, using optional chaining here would make it throw on many of the supported browsers.
> 
> Also, if you don't include `typeof self === "undefined"`, it can still throw in your environment.

Sorry about that, I've so far only worked on bigger projects that get `Babel`ed. Force of habit.

**Comment by LeaVerou** [comment]
Merged, thanks!

**Pull request merged**
