### PR TITLE
avoid multiple initialization

### PR DESCRIPTION
**Pull request by salvan13**

### CODE REVIEW

**Comment by LeaVerou** [comment]
Thanks, but it's easier to just check if it has the class `multirange`, instead of adding an extra attribute. Wanna try that? :)

**Comment by LeaVerou** [comment]
Thanks! However, I recently refactored the init code to account for usage in `<head>` (https://github.com/LeaVerou/multirange/commit/be92febef6d31d4551f060550077e4782d2e3154) and as part of that I added a `:not(.multirange)` to the selector which also prevents multiple intialization. Sorry!
Thank you for contributing though!

**Comment by salvan13** [comment]
It's OK, I like your solution  :thumbsup:

**Comment by salvan13** [comment]
But... what if someone calls multirange(input) twice?

**Comment by LeaVerou** [comment]
Ouch, good point. Yeah, it needs to check in `multirange()` as well. Can you simplify this PR to just check for `classList.contains("multirange")`? I'd rather keep this small.

**Pull request closed without merging**
