### PR TITLE
Added a package.json to support install via npm

### PR DESCRIPTION
**Pull request by allbinmani**

### CODE REVIEW

**Comment by dy** [comment]
`module.exports = multirange;` would be also really appreciated!

**Comment by allbinmani** [comment]
I think this branch is ready for merge now?

**Comment by LeaVerou** [comment]
Thanks for contributing! I was traveling so I'm a bit behind on Github. I would love to merge the package.json, but there are also some indentation changes that need to be reverted or justified.

**Comment by LeaVerou** [comment]
Also we don't use JSHint on this project. If I get a minute, I'll add an ESLint config file.

**Comment by rasben** [comment]
So.. what ever happened to this one? @LeaVerou

**Comment by LeaVerou** [comment]
@rasben nobody fixed the indentation issues I mentioned, that's what happened.

**Comment by allbinmani** [comment]
@LeaVerou Could you please specify further what you refer to with "some indentation changes"? Checked the patch and not sure what you mean. Thanks!

**Comment by LeaVerou** [comment]
Spaces have been used for indentation.

**Comment by rasben** [comment]
This has been merged in https://github.com/LeaVerou/multirange/pull/26 and can be closed @allbinmani

**Comment by LeaVerou** [comment]
Apparently this completely broke the script and causes errors of module not being defined.
See: https://github.com/LeaVerou/multirange/issues/27 (except this is not just in IE, it happens in my Chrome too)
Did you not test this before submitting this PR?

**Comment by allbinmani** [comment]
It's been a year and a half since I used multirange in a project. That project is live, and afaik working as intended. However, it was most likely built using webpack or browserify, and did not include multirange 'directly' in a page.

**Pull request closed without merging**
