### PR TITLE
Expose API via CommonJS instead of a global variable, when supported

### PR DESCRIPTION
**Pull request by markasoftware**
Much nicer for us browserify folks.

### CODE REVIEW

**Comment by LeaVerou** [comment]
I was ready to merge this, then noticed the version change in package.json. Could you please revert that? Even if we do release a new version, this does not warrant such a major release.

Thanks for contributing!

**Comment by markasoftware** [comment]
[Semver](https://semver.org) dictates that any breaking change should include a new major version — even if the change is small. Angular, for example, went from version 2 to 4 without any massive upheaval. If the major version is kept the same, unwitting consumers of this package will receive the new version automatically and their apps will break.

**Comment by LeaVerou** [comment]
Why is this a breaking change? Won't it still have a global when a global is desired?

**Comment by markasoftware** [comment]
CommonJS modules don't usually set globals, so I disabled the global when CommonJS modules are supported, for better or for worse.

**Comment by LeaVerou** [comment]
Yes but people couldn't use this as a module before, so how is it a breaking change? For people not using it as a module, it will still have the global...no?

**Comment by markasoftware** [comment]
What was the purpose of the npm package before this PR? As I understand it, it was to do things like this using browserify:

```
require('multirange')
multirange(myElement)
```

This would no longer function after this PR; you would need `var multirange = require('multirange')`. If you are fine with breaking the few apps that may have used it like the example at top, let me know and I'll revert the version.

**Comment by LeaVerou** [comment]
Hmm, nah, you convinced me, I guess the version bump makes sense. I'll merge it as-is. Thanks for contributing!

**Pull request merged**
