### PR TITLE
Changed Array.from to another method supported by IE

### PR DESCRIPTION
**Pull request by decemberly**
#22

### CODE REVIEW

**Comment by LeaVerou** [comment]
This won't work in IE11 anyway, it requires CSS Variable support. Thanks for contributing though!

**Comment by decemberly** [comment]
Sure, it won't be a multirange, but I needed that change do display the two fallback sliders, otherwise I just get a JavaScript error and one slider (which is just confusing).

**Comment by LeaVerou** [comment]
So you've tested this and it improves the experience in IE11? If so, I will merge it.

**Comment by decemberly** [comment]
Yes, I've tested it and it does improve the experience in IE11.

**Comment by LeaVerou** [comment]
Thanks, merged!

**Pull request merged**
